# docker-compose.yml

services:
  # Dịch vụ Database (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: Anchinlu      
      POSTGRES_PASSWORD: 110122027  
      POSTGRES_DB: cine_booking_db      
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # ---- THÊM HEALTHCHECK CHO DATABASE ----
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Anchinlu -d cine_booking_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Dịch vụ Backend (NestJS)
  backend:
    build:
      context: ./backend
    container_name: backend_service
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./backend/.env
    # ---- SỬA LẠI DEPENDS_ON ----
    depends_on:
      db:
        condition: service_healthy # Chỉ khởi động khi db đã "healthy"

  # Dịch vụ Frontend (Next.js)
  frontend:
    build:
      context: ./frontend
    container_name: frontend_service
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    stdin_open: true
    tty: true
    # ---- THÊM DEPENDS_ON CHO FRONTEND ----
    depends_on:
      - backend # Đảm bảo frontend khởi động sau backend

volumes:
  postgres_data: