
services:
  # Dịch vụ Database (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: Anchinlu      
      POSTGRES_PASSWORD: 110122027  
      POSTGRES_DB: cine_booking_db      
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Dịch vụ Backend (NestJS)
  backend:
    build:
      context: ./backend
    container_name: backend_service
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - db

  # Dịch vụ Frontend (Next.js)
  frontend:
    build:
      context: ./frontend
    container_name: frontend_service
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    stdin_open: true
    tty: true

volumes:
  postgres_data: