services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: Anchinlu
      POSTGRES_PASSWORD: 110122027
      POSTGRES_DB: cine_booking_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Anchinlu -d cine_booking_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    container_name: backend_service
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    # --- THAY ĐỔI HEALTHCHECK CỦA BACKEND ---
    # Alpine không có sẵn wget, dùng một script nhỏ với nc (netcat) để kiểm tra
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8080"]
      interval: 5s
      timeout: 5s
      retries: 10

  frontend:
    build:
      context: ./frontend
    container_name: frontend_service
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      backend:
        condition: service_healthy # Yêu cầu frontend chờ cho đến khi backend "khỏe mạnh"

volumes:
  postgres_data: