# file: .github/workflows/frontend-ci.yml

name: Frontend CI

on:
  push:
    branches: [ "fix/ci-cd-lint-errors" ]
  pull_request:
    branches: [ "fix/ci-cd-lint-errors" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm' 
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

      - name: Build project
        run: npm run build